services:

  # Local services are available on their ports, but also available on:
  # http://api.localhost.tiangolo.com: backend
  # http://dashboard.localhost.tiangolo.com: frontend
  # etc. To enable it, update .env, set:
  # DOMAIN=localhost.tiangolo.com
  proxy:
    image: traefik:3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8090:8080"
    # Duplicate the command from docker-compose.yml to add --api.insecure=true
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label for this stack
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.https.address=:443
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable debug logging for local development
      - --log.level=DEBUG
      # Enable the Dashboard and API
      - --api
      # Enable the Dashboard and API in insecure mode for local development
      - --api.insecure=true
    labels:
      # Enable Traefik for this service, to make it available in the public network
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      # Dummy https-redirect middleware that doesn't really redirect, only to
      # allow running it locally
      - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
    networks:
      - traefik-public
      - default

  db:
    restart: "no"
    ports:
      - "5432:5432"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./backend
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./backend/htmlcov:/app/htmlcov
      - ./backend/app/alembic:/app/app/alembic
    environment:
      SMTP_HOST: "mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend-network # Ensure it's on the same network as backend

  neo4j:
    ports:
      - "7474:7474"  # HTTP (optional, for Neo4j Browser)
      - "7687:7687"  # Bolt (used by the Python driver)

  # Add Redis Service Override (e.g., for exposing port)
  redis:
    ports:
      - "6379:6379" # Expose Redis port to host
    networks:
      - backend-network
      - default # Ensure it's on all networks
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-redispassword} --protected-mode no --bind 0.0.0.0
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
  # Add Flower service override to expose port locally
  flower:
    ports:
      - "5555:5555"  # Expose Flower port to host
    restart: "no"    # Don't restart automatically in development
    networks:
      - backend-network
      - default
      - traefik-public
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH:-}  # Optional: add basic auth for local dev
      - FLOWER_URL_PREFIX=${FLOWER_URL_PREFIX:-}  # Optional: URL prefix if needed

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false

volumes:
  # ... existing volumes ...
  redis_data:
    driver: local
