"""Remove user_id from ThreadView table

Revision ID: 21f71a1ed14e
Revises: 1fcb12fe7e09
Create Date: 2025-04-12 11:15:16.015443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21f71a1ed14e'
down_revision = '1fcb12fe7e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('threadview_user_id_fkey', 'threadview', type_='foreignkey')
    op.drop_column('threadview', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threadview', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('threadview_user_id_fkey', 'threadview', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
